from fastmcp import FastMCP

mcp = FastMCP("Movie Workflow MCP")

@mcp.tool()
def summarize_movie_review(review: str):
    return {"summary": "Short summary generated by LangChain"}

if __name__ == "__main__":
    mcp.run(transport="http")